### ISSUE TITLE
Github pages hosting not yet fully functional

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/brainhack-2018-website#10]
Dunno if you are already aware, but the generated URLs for the site hosted on github pages have a leading dot, which screws up the navigation links (and it seems also the CSS refs). Example URL: https://psychoinformatics-de.github.io/brainhack-2018-website/.projects.html

@bpoldrack @aqw could you please check what is going on (not sure who is closer to the source of this issue)?

**Comment by aqw** [comment]
I was unaware. Thanks for the heads up.

**Comment by aqw** [comment]
Seems to still be a problem. WTF.

**Comment by aqw** [comment]
BAM. FIXED.

Yup, I broke it in: 373dec856d8fc992c1280b1d9d4dea4294b0ceb2

The fix was to add ``output/`` to the .gitignore file in the gh-pages branch. Sigh....
