### ISSUE TITLE
Preferred way to populate details.html?

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/brainhack-2018-website#9]
IIRC we did not envision much styling for this page. @aqw do you think an rst source file would be a good approach. Would be easy to edit by hand right here on github.

**Comment by aqw** [comment]
I'm cool with either way. We can either mimic the card setup from the front page (pretty, but I don't think it exactly a great match for the content) or just go for a normal .rst file and straight content and then I'll come up with something that makes it kinda match the look'n'feel of the rest of the site.

**Comment by mih** [comment]
Ok, let's use an RST file for now and see to what content that will lead to. Can you prepare one please?

**Comment by aqw** [comment]
The page will need some styling, but we'll roll with it as-is for now.
